baseURL = "https://sumithpdd.github.io/JAMSite/"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2020 Sumith"
disableKinds =["section"]

[outputs]
  home = ["HTML","JSON"]
